### ISSUE TITLE
Server init fails to run on Stratis

### ISSUE THREAD

**Issue by hehe3301** [AdamWaldie/A3-CAVASTASI#1]
Loading in to Stratis, no init run, cannot interact with any base objects

**Comment by AdamWaldie** [comment]
Evening, thank you for the report.

I am unable to replicate the bug. I just attempted this on TS3. I did not load the last save in the parameters from the slot screen. 

I believe that this bug may be due to old CAVASTASI mission saves in the player profile, which are **incompatible** with 2.3 series versions. As such. **I advise all players to disable "Load Last Persistent Save" in the mission parameters when starting a new map for the first time.**

![20200803161550_1](https://user-images.githubusercontent.com/35147137/89198308-f16c9780-d5a4-11ea-9f47-be844f7c5205.jpg)
![20200803161556_1](https://user-images.githubusercontent.com/35147137/89198336-f9c4d280-d5a4-11ea-8c98-3f3f56051ba4.jpg)
![20200803161601_1](https://user-images.githubusercontent.com/35147137/89198380-0c3f0c00-d5a5-11ea-8c55-5967b5519ce9.jpg)
![20200803161607_1](https://user-images.githubusercontent.com/35147137/89198385-0e08cf80-d5a5-11ea-8cf2-8b53af3c13d2.jpg)
![20200803161618_1](https://user-images.githubusercontent.com/35147137/89198392-106b2980-d5a5-11ea-93ca-729e90e46e28.jpg)
